version: '3.4'

services:
  mssqldb:
    container_name: 'mssqldb'
    build:
       dockerfile: ./Database/Dockerfile
    ports:
      - "1433:1433"

  abptestapp:
    image: ${DOCKER_REGISTRY-}abptestapp
    container_name: 'abptestapp'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=mssqldb;Database=ABPTestDB;User=sa;Password=1Secure*Password1
      - REDIS_CONNECTION_STRING=redis:6379,abortConnect=False
    depends_on:
      - mssqldb
      - redis

  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"